monolog:
  channels:
    - application_import_template
    - application_import
    - application_export
    - application_communication_nsia
    - app_mailer

  handlers:
    application_import_template:
      type: group
      members: [ application_import_template_console ]
    application_import:
      type: group
      members: [ application_import_console ]
    application_export:
      type: group
      members: [ application_export_console ]
    application_communication_nsia:
      type: group
      members: [ application_communication_nsia_console ]
    app_mailer:
      type: group
      members: [ app_mailer_console ]

    application_import_template_console:
      type: stream
      path: "php://stdout"
      level: debug
      channels: [ "application_import_template" ]

    application_import_console:
      type: stream
      path: "php://stdout"
      level: debug
      channels: [ "application_import" ]

    application_export_console:
      type: stream
      path: "php://stdout"
      level: debug
      channels: [ "application_export" ]

    application_communication_nsia_console:
      type: stream
      path: "php://stdout"
      level: info
      channels: [ "application_communication_nsia" ]

    app_mailer_console:
      type: stream
      path: "php://stdout"
      level: debug
      channels: [ "app_mailer" ]
