# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    google:
        enabled: true
        server_name: '%env(MFA_SERVER_NAME)%'           # Server name used in QR code TODO: move to config [GDA]
        issuer: 'Cassa Commercio Liguria'               # Issuer name used in QR code
        digits: 6                                       # Number of digits in authentication code
        leeway: 5                                       # Acceptable time drift in seconds, must be less or equal than 30 seconds
        template: admin/2fa-verify.html.twig            # Template used to render the authentication form
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
