FROM wodby/nginx:1.21-5.17.4
USER root

COPY .config/nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh   
RUN chown -R nginx:nginx /var/cache/nginx /usr/share/nginx/ /var/run/nginx /nginx-entrypoint.sh /etc/nginx/

USER nginx
#ENTRYPOINT ["/nginx-entrypoint.sh"]
ENTRYPOINT ["/bin/bash", "/nginx-entrypoint.sh"]
CMD ["nginx"]

EXPOSE  80
