FROM wodby/nginx:1.21-5.17.4
USER root

COPY .config/nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh   
RUN cp -R /etc/nginx /etc/nginx-orig
RUN sed -i 's|listen 80 default_server|listen 8080 default_server|g' /etc/gotpl/vhost.conf.tmpl
RUN gotpl "/etc/gotpl/50x.html.tmpl" "/usr/share/nginx/html/50x.html"
RUN chown -R wodby:wodby /var/cache/nginx /usr/share/nginx/ /var/run/nginx /nginx-entrypoint.sh /etc/nginx/ /etc/nginx-orig
USER wodby
#ENTRYPOINT ["/nginx-entrypoint.sh"]
ENTRYPOINT ["/bin/bash", "/nginx-entrypoint.sh"]
CMD ["nginx"]

EXPOSE  8080
