FROM wodby/nginx:1.21-5.17.4
USER root

COPY .config/nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh   
RUN cp -R /etc/nginx /etc/nginx-orig
RUN chown -R wodby:wodby /var/cache/nginx /usr/share/nginx/ /var/run/nginx /nginx-entrypoint.sh /etc/nginx/ /etc/nginx-orig

USER wodby
WORKDIR /var/www/html
COPY . .
ENTRYPOINT ["/bin/bash", "/nginx-entrypoint.sh"]
CMD ["nginx"]
EXPOSE  80
