trigger: 'none'

variables:
  - group: aws-config-prod
  - group: liguria-ccl-env-vars-production

jobs:
  - job: ProcessRoutineNSIA
    pool: 'ArtigiancassaAWSPool'
    displayName: 'Process routine NSIA'
    steps:
      - task: SystemsManagerRunCommand@1
        inputs:
          awsCredentials: '$(AWS_CREDENTIAL)'
          regionName: '$(NSIA_AWS_REGION)'
          documentName: 'AWS-RunShellScript'
          documentParameters: '{"workingDirectory":["/var/app/current"],"executionTimeout":["3600"],"commands":["sudo -u webapp bin/routine-nsia.sh"]}'
          instanceSelector: 'fromTags'
          instanceTags: 'worker-nsia=ccl'
          maxConcurrency: '1'
          maxErrors: '1'
          outputS3BucketName: 'liguria-nsia-log-ssm-command'
          outputS3KeyPrefix: 'ccl'
