<?php
echo "aAAAAAAAAaaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAAaAAAAAAAA!";

if (file_exists(dirname(__DIR__).'/var/PROD/App_KernelProdContainer.preload.php')) {
    require dirname(__DIR__).'/var/PROD/App_KernelProdContainer.preload.php';
}
